services:
  bootcamp-ms-eureka-server:
    image: bootcamp-ms-eureka-server:latest
    container_name: bootcamp-ms-eureka-server
    ports:
      - 8761:8761
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true